spring:
    profiles.active: dev
    application.name: swagger2markup-demo

server:
    port: 9080

info:
    name: ${spring.application.name}
    description: Swagger2Markup demo
    environment: ${spring.profiles.active}
    version: 1.0.0